version: '3.7'

services:
  web:
    build:
      context: .
      target: development
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    ports:
      - ${HTTP_PORT}:3000
      - 9229:9229
    command: npm run start:dev
    networks:
      - webnet
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    volumes:
      - ./database:/var/lib/postgresql/data
    env_file:
      - .env
    environment: 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
        - "${DB_PORT}:5432"
networks:
  webnet: