version: '3.7'

services:
  web:
    build:
      context: .
      target: development
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:dev
    networks:
      - webnet
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    volumes:
      - ./database:/var/lib/postgresql/data
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: admin
    ports:
        - 5433:5432
networks:
  webnet: