version: '3.7'

services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./database:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD:'${DB_PASSWORD}'
      - POSTGRES_USER:'${DB_USER}'
      - POSTGRES_DB:'${DB_NAME}'
    ports:
      - '${DB_PORT}:5432'

  api:
    build:
      context: ./
      target: development
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    command: yarn start:dev
    depends_on:
      - postgres
